### ISSUE TITLE
Update code to ES6 library structure

### ISSUE THREAD

**Issue by pwalsh** [frictionlessdata/jsontableschema-js#15]
# Description

We are writing our libraries in ES6 going forward ( https://github.com/okfn/coding-standards#javascript ). The way we are writing our libraries is based on patterns established in major JS projects such as [Redux](https://github.com/reactjs/redux). 

Before we add new functionality to this lib, we'll port it to this structure so we are in good stead to go forward with refactoring and features.

## Examples

We have a few code bases using ES6 and/or modern build processes now, for reference:

- https://github.com/okfn/data-quality-dashboard
- https://github.com/frictionlessdata/datapackage-registry-js
- https://github.com/openspending/babbage.ui/tree/feature/modern

Not all these libraries are the same in the way they implement things. They are linked here just for potential reference, FYI. We are working towards a workable standard to codify in our [coding standards](https://github.com/okfn/coding-standards#javascript).

# Tasks

- [x] Move code into `src`, then port the existing code to ES6. Favour `let` and `const` over `var` (you should rarely need `var`), and favour [arrow functions](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Functions/Arrow_functions) where it makes sense
- [x] Port the tests to ES6, and get them working. [Here is how to get `mocha` running with ES6](https://github.com/openspending/babbage.ui/blob/feature/modern/test/mocha.opts)
- [x] Setup the scripts so we can build out `lib` (for distributing ES5) and `dist` (for browsers). See [here](https://github.com/openspending/babbage.ui/blob/feature/modern/package.json#L7) and [here](https://github.com/openspending/babbage.ui/blob/feature/modern/package.json#L8) and [here](https://github.com/openspending/babbage.ui/blob/feature/modern/package.json#L18) and [here](https://github.com/openspending/babbage.ui/blob/feature/modern/.npmignore) and [here](https://github.com/openspending/babbage.ui/blob/feature/modern/.gitignore#L9) and [here](https://github.com/openspending/babbage.ui/blob/feature/modern/webpack.config.base.js) and [here](https://github.com/openspending/babbage.ui/blob/feature/modern/webpack.config.development.js) and [here](https://github.com/openspending/babbage.ui/blob/feature/modern/webpack.config.production.js) :)
- [x] Configure `eslint`

**Comment by pwalsh** [comment]
looks good!
