### ISSUE TITLE
Complete the port of the Python library

### ISSUE THREAD

**Issue by pwalsh** [frictionlessdata/jsontableschema-js#16]
# Description

# Tasks

- [x] What is currently called `ensure` needs to become `validate`: https://github.com/frictionlessdata/jsontableschema-py/blob/master/jsontableschema/validate.py
  - [x] Check existing logic is valid
  - [x] Add any required additional logic to be consistent with Python lib
- [x] Check `infer` and make consistent with https://github.com/frictionlessdata/jsontableschema-py/blob/master/jsontableschema/infer.py
- [x] What is currently `models` needs to become `model`: https://github.com/frictionlessdata/jsontableschema-py/blob/master/jsontableschema/model.py
  - [x] Check we have all methods. I know that some methods to deal with data are missing
  - **Note**: This is an area for improvement in the Python lib too. See [we are discussing it](https://github.com/frictionlessdata/jsontableschema-py/issues/34). So do not sweat over details here. Perhaps you'll have suggestions for how we can improve the interface.
- [x] Check `types` and make consistent with Py version. This means adding lots of things not in the JS version yet, to do with constraints
- [x] **Remove** direct dependency on Bluebird. As this is a low-level utility library, we want to remove bloat. As part of instructions, we need to tell users that they need a runtime that supports promises (as Node, Chrome, Firefox, Safari do), or they add their own polyfill.
- [x] Tests: we need very good unit test coverage on every function

**Comment by pwalsh** [comment]
Noting that the GeoJSON type on the Python lib uses a schema to validate, included as a file in the codebase. I'll put that file online somewhere and we'll use it with a HTTP request here in the JS lib for smoother Node/Browser compat. Ping me when this is needed.

**Comment by pwalsh** [comment]
@zhenyab a few additions before we merge:

- [ ] Rename `model.js` to `schema.js` (and allow importing `Schema` directly from `jsontableschema`)
- [ ] `Schema.schema` to `Schema.descriptor` (to be consistent with some [naming changes on other related libs](https://github.com/frictionlessdata/datapackage-py/issues/88)
  - https://github.com/frictionlessdata/jsontableschema-js/blob/feature/port-python/src/model.js#L276

**Comment by pwalsh** [comment]
DONE.
