### ISSUE TITLE
Add Resource interface to read data

### ISSUE THREAD

**Issue by pwalsh** [frictionlessdata/jsontableschema-js#22]
# Description

JSON Table Schema provides us with really useful information to understand the data in a delimited value text file. Of course, one of the most common use cases is that data is transported in such text files, and then when we want to use the data, we read it out of the file and into some data storage: anything from an array in memory, through to an SQL table.

To facilitate the flow of:

1. Open
2. Read
3. Cast
4. Store

We implement the `Resource` class to provide a consistent way to perform steps 2 and 3 (and later, step 1).

## API

- Note similar code in here which should be used as possible: https://github.com/frictionlessdata/datapackage-render-js/blob/master/datapackage.js#L83
- Both `schema` and `data` could be one of a local path, a url, a readable stream, a file buffer. Data could also be an array. And, probably other possibilities too, across node and browser runtimes... For the first iteration of resource, we do not want to deal with opening files, URLs and so on, so code the first implementation where schema is already an instance of a schema model, and data is already a readable stream

```
class Resource(schema, data, headers=None, name=None)
  schema = this._getSchema(schema) // make an instance of a schema model.
  data = this._getData(data) // get a stream (?) over the data
  headers = this._getHeaders(data, headers) // passed in headers, or, from first row of data
  descriptor = this._makeDescriptor() // makes a basic, DataPackage-compatible Resource descriptor for this Resource
  // { name: name, path: '', schema: schema.descriptor }
  iter() = // returns an iterator over data, and each row can be `cast`
  _uniques = {} // object to store seen values for unique fields, where key is the field name, and value is an array of seen values
```

```
# usage: something like
const data = // an iterable over the data
const schema = // a schema model object
const resource = new Resource(schema, data)

for (let row or resource.iter()) {
  try {
    row.cast()
    // can access the raw source data as array in `row`
    // can access the cast data with `row.cast()`
    // DO things here, like write the cast data to a storage backend
  } catch (e if e instanceof RowCastError) {
    // catch errors if row cannot be cast
  } catch (e if e instanceof UniqueConstraintError) {
    // catch errors on unique constraints. requires that we build up arrays of data for columns with unique true
  }
  // etc.
}
```

# Tasks

- [x] Resource class with basic methods to read data
- [x] Functionality to cast each row as it is read
- [x] Write the unique constraint from JTS as a constraint, and implement it on the Resource where we can now actually check it
- [x] Update documentation
- [x] Unit tests
More discussion at: 

- https://github.com/frictionlessdata/jsontableschema-py/issues/34#issuecomment-222066447

**Comment by pwalsh** [comment]
@zhenyab several example datasets here https://github.com/frictionlessdata/testsuite-py/tree/master/datasets

**Comment by zhenyab** [comment]
Should be Resource class available for public use, or it's for internal usage only?

**Comment by pwalsh** [comment]
public.
