### ISSUE TITLE
Release jsontableschema-v0.2

### ISSUE THREAD

**Issue by roll** [frictionlessdata/jsontableschema-js#36]
# Overview

We need to establish regular release process here.
@zhenyab do you think we're ready?
@akariv is it ok to have next 0.2.0, 0.3.0 etc version with possible breaking changes?

# Tasks

- [x] decide on supported node versions and add it to `package.json` and `.travis.yml` (esp. important to test it)
- [x] remove babel and build stage if supported node version is enough to handle this code (new imports are not so important to have in my opinion if it will be the only one things for babel)
- [x] finish release description - https://github.com/frictionlessdata/jsontableschema-js/releases/edit/untagged-881331bc6b9cf911d03a

**Comment by zhenyab** [comment]
@roll Library does not have all functionality like Resource, Storage etc., but it is improved version

**Comment by roll** [comment]
I think it's doesn't matter (we have next versions for it=) but it will be cool to have some starting point. I'm more concerned about our release process - we need to automaticaly release on npm when we will push `publish` button here - https://github.com/frictionlessdata/jsontableschema-js/releases/edit/untagged-881331bc6b9cf911d03a)

**Comment by roll** [comment]
@zhenyab 
I've added https://github.com/frictionlessdata/jsontableschema-js/labels/v0.2 label as high-level check-list for the release.

**Comment by roll** [comment]
@pwalsh 
@zhenyab 
I've prepared travis for auto-releasing on tags created but GitHub releases. But moving this card from current for now and re-assigning @zhenyab because in my opinion we need to specify node version we support (for now it's only `6.1` in travis - in this case we could remove all those transpiling things).

**Comment by roll** [comment]
@zhenyab 
Also if it's not urgent for `ebola-tracker` we could include API sync (https://github.com/frictionlessdata/jsontableschema-js/issues/38) to the release.

**Comment by roll** [comment]
@zhenyab 
@pwalsh 
@akariv 
returning to our node js versions discussion:
![703-imported-1453533598-schedule](https://cloud.githubusercontent.com/assets/557395/18319753/c9940b96-752f-11e6-9160-996dcbd4cbf1.png)
Based on this good to be support two (for now) LTS branches - v4 and v6. 
But if everyone is OK to start with v6 (as Paul's said if I've got it right) there is no need in all of webpack-babel stuff complicating development process (here and in future parts of the js stack).
WDYT?

**Comment by roll** [comment]
But with babel we could be able to provide version for browsers sometimes. 

So safest bet looks like stick with transpiling and suppose `node-v4` and `node-v6`.

**Comment by pwalsh** [comment]
We only need v6 for dev. We already also generate a version for all node versions, and a browser dist.

**Comment by roll** [comment]
@pwalsh 
thanks! I was asking a little bit a different thing but now all is clear for me)

So I can release `v0.2` now. Other option if @zhenyab will be having time to fix  https://github.com/frictionlessdata/jsontableschema-js/issues/38 soon it will be better to do it before the release because it's breaking.

But I have no strong preference here.

**Comment by pwalsh** [comment]
Let's do #38 for v0.2 then, and ensure we have a change log to document the API changes from the current npm version

**Comment by roll** [comment]
@pwalsh 
:+1: 

changelog - https://github.com/frictionlessdata/jsontableschema-js/releases/edit/untagged-881331bc6b9cf911d03a (it's a part of tasks for this issue)

**Comment by roll** [comment]
No need to track this way. Will be released after https://github.com/frictionlessdata/jsontableschema-js/issues/38 hit the master
